import Link from'next/link';import{ArrowRight,Building2,Gift,HeartHandshake,PackageCheck,ShieldCheck,Sparkles,Truck}from'lucide-react';import type{HomepageSection,Product}from'@/lib/types';import{HeroSlider,type HeroBanner}from'./hero-slider';import{OccasionSlider}from'./occasion-slider';import{ProductCarousel}from'./product-carousel';import{Reveal}from'./reveal';import{AdaptiveImage}from'./adaptive-image';
const recipients=[['For Her','#f7d8dc','♥'],['For Him','#dce8f1','✦'],['For Couples','#eadff2','∞'],['For Parents','#f4e2cc','⌂'],['For Bestie','#f4dcea','☺'],['For Kids','#dbeee5','★']];
type Category={id:string;name:string;slug:string;imageUrl?:string|null};
type Testimonial={id:string;name:string;quote:string;rating:number};
type Reel={id:string;title:string;caption:string;videoUrl:string;thumbnailUrl?:string};
export function HomepageSections({sections,products,banners,testimonials,reels,categories=[]}:{sections:HomepageSection[];products:Product[];banners:HeroBanner[];testimonials:Testimonial[];reels:Reel[];categories?:Category[]}){return <>{sections.filter(s=>s.enabled).sort((a,b)=>a.sortOrder-b.sortOrder).map(section=><HomepageSectionView key={section.id} section={section} products={products} banners={banners} testimonials={testimonials} reels={reels} categories={categories}/>)}</>}
function HomepageSectionView({section,products,banners,testimonials,reels,categories}:{section:HomepageSection;products:Product[];banners:HeroBanner[];testimonials:Testimonial[];reels:Reel[];categories:Category[]}){switch(section.type){case'hero_slider':return <HeroSlider banners={banners}/>;
case'category_circles':return null;
case'recipient_collection':return <Reveal><section className="section shell category-section"><div className="section-heading centered"><span className="eyebrow">GIFTING MADE PERSONAL</span><h2>Made for their kind of wonderful</h2><p>Start with them. We’ll help with the magic.</p></div><div className="category-grid">{(categories.length?categories:recipients.map(([name])=>({id:name,name,slug:name.toLowerCase().replaceAll(' ','-')}))).map(category=><Link href={`/category/${category.slug}`} className="category-card" key={category.id}><span>{typeof (category as Category).imageUrl==='string'?<AdaptiveImage src={(category as Category).imageUrl as string} alt={category.name} width={320} height={320}/>:<Gift/>}</span><strong>{category.name}</strong></Link>)}</div></section></Reveal>;
case'product_grid':return <Reveal><section className="section product-section"><div className="shell"><div className="section-heading split"><div><span className="eyebrow">MOST-LOVED GIFTS</span><h2>{section.title}</h2><p>{section.subtitle??'Thoughtful, beautiful and ready to make their day.'}</p></div><Link href="/shop" className="text-link">View all gifts <ArrowRight/></Link></div><ProductCarousel products={products.slice(0,12)} label="Most-loved GiftsByRashii products"/></div></section></Reveal>;
case'occasion_collection':return <Reveal><section className="section occasion-section"><div className="section-heading centered shell"><span className="eyebrow">MOMENTS WORTH CELEBRATING</span><h2>{section.title}</h2><p>{section.subtitle??'Find the feeling first. The perfect gift follows.'}</p></div><OccasionSlider products={products.slice(0,7)}/></section></Reveal>;
case'price_collection':return <Reveal><section className="price-section section"><div className="shell"><div className="section-heading centered"><span className="eyebrow">BEAUTIFUL AT EVERY BUDGET</span><h2>{section.title}</h2></div><div>{[499,999,1499,2499].map((p,i)=><Link key={p} href={`/shop?maxPrice=${p}`}><span>{['Little joys','Thoughtful favourites','Extra special','The grand gesture'][i]}</span><b>Under ₹{p}</b><ArrowRight/></Link>)}</div></div></section></Reveal>;
case'custom_hamper':return <Reveal><section className="hamper-banner shell"><div><span className="eyebrow"><Sparkles/>MADE BY YOU</span><h2>{section.title}</h2><p>Choose the box, handpick every goodie, add their name and write from the heart.</p><Link href="/hamper-builder" className="button button-primary">Build a one-of-one hamper <ArrowRight/></Link></div><div className="hamper-banner-art"><span><Gift/></span><i>+ chocolates</i><i>+ candle</i><i>+ keepsake</i></div></section></Reveal>;
case'corporate_gifting':return <Reveal><section className="corporate-home"><div className="shell"><div><span className="eyebrow">CORPORATE, BUT NEVER COLD</span><h2>{section.title}</h2><p>Brand-right gifting for employees, clients and milestone moments—curated, customised and delivered across India.</p><Link href="/corporate-gifting" className="button button-primary">Explore corporate gifting</Link></div><div className="corporate-mini-grid">{[Building2,PackageCheck,Truck,HeartHandshake].map((Icon,i)=><span key={i}><Icon/><b>{['Custom branding','Scale-ready','Pan-India','Human support'][i]}</b></span>)}</div></div></section></Reveal>;
case'testimonials':return testimonials.length?<Reveal><section className="section testimonial-section shell"><div className="section-heading centered"><span className="eyebrow">LOVE, DELIVERED</span><h2>{section.title}</h2></div><div>{testimonials.map(item=><blockquote key={item.id}>“{item.quote}”<cite>— {item.name} · {'★'.repeat(item.rating)}</cite></blockquote>)}</div></section></Reveal>:null;
case'reels':return reels.length?<Reveal><section className="section managed-reels shell"><div className="section-heading centered"><span className="eyebrow">WATCH THE JOY</span><h2>{section.title}</h2></div><div>{reels.map(item=><article key={item.id}><video src={item.videoUrl} poster={item.thumbnailUrl} controls playsInline preload="metadata"/><b>{item.title}</b>{item.caption&&<p>{item.caption}</p>}</article>)}</div></section></Reveal>:null;
case'usp':return <section className="usp-strip"><div className="shell">{[[ShieldCheck,'Payments verified','Secure gateway confirmation'],[Gift,'Beautifully packed','Every unboxing matters'],[Truck,'Delivery clarity','Pincode-based estimates'],[HeartHandshake,'Human support','Real help when needed']].map(([Icon,title,text])=><span key={String(title)}><Icon/><b>{String(title)}</b><small>{String(text)}</small></span>)}</div></section>;
case'newsletter':return <section className="newsletter-section"><div><Sparkles/><span className="eyebrow">A LITTLE JOY IN YOUR INBOX</span><h2>{section.title}</h2><p>Fresh gifting ideas and members-only surprises. No clutter.</p><form action="/api/newsletter" method="post"><input name="email" type="email" required placeholder="Your email address"/><button>Join the joy →</button></form></div></section>;
default:return null}}
