'use client';
import Link from'next/link';
import{Gift,Heart,Home,LogIn,Menu,PackageSearch,Search,ShoppingBag,Sparkles,UserRound,X}from'lucide-react';
import{useEffect,useState}from'react';
import{usePathname}from'next/navigation';
import{useCart}from'./cart-provider';
type StoreConfig={navigation?:{label:string;url:string}[];announcements?:{text:string}[];settings?:{shipping?:{freeShippingAbove?:number};store?:{name?:string;supportEmail?:string;supportPhone?:string;whatsapp?:string};social?:Record<string,string>}};
type SessionState={authenticated:boolean;fullName?:string};
export function Logo(){return <Link href="/" className="brand" aria-label="GiftMitra home"><span className="brand-gift"><Gift size={18}/></span><span>Gift<span>Mitra</span></span></Link>}
const defaults=[['Home','/'],['New & Noteworthy','/shop'],['Occasions','/occasion/birthday'],['Recipients','/recipient/for-her'],['Personalised','/category/personalised-gifts'],['Build a Hamper','/hamper-builder'],['Corporate Gifting','/corporate-gifting']];
export function SiteHeader(){
 const[open,setOpen]=useState(false);const[links,setLinks]=useState(defaults);const[session,setSession]=useState<SessionState>({authenticated:false});const[announcement,setAnnouncement]=useState('Use HELLO10 for 10% off your first gift');const[shipping,setShipping]=useState('Free shipping above ₹999 · Made with love in India');const{count,wishlist}=useCart();const pathname=usePathname();
 useEffect(()=>{Promise.all([fetch('/api/storefront-config').then(async r=>(await r.json()) as StoreConfig),fetch('/api/auth/session',{cache:'no-store'}).then(async r=>(await r.json())as SessionState)]).then(([data,auth])=>{if(data.navigation?.length){const managed=data.navigation.map(x=>[x.label,x.url]);setLinks(managed.some(([,url])=>url==='/')?managed:[['Home','/'],...managed])}if(data.announcements?.[0])setAnnouncement(data.announcements[0].text);if(data.settings?.shipping?.freeShippingAbove)setShipping(`Free shipping above ₹${data.settings.shipping.freeShippingAbove} · Made with love in India`);setSession(auth)}).catch(()=>{})},[]);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',close)}},[open]);
 const isActive=(url:string)=>{const target=url.split('?')[0];return target==='/'?pathname==='/':pathname===target||pathname.startsWith(`${target}/`)};const accountHref=session.authenticated?'/account':'/login';
 return <><div className="announcement"><span><Sparkles size={14}/>{announcement}</span><span className="announcement-extra">{shipping}</span></div><header className="site-header"><div className="header-main shell"><button className="mobile-menu" onClick={()=>setOpen(true)} aria-label="Open menu" aria-expanded={open}><Menu/></button><Logo/><form className="search-box" action="/search"><Search size={18}/><input name="q" aria-label="Search gifts" placeholder="Search gifts, people or occasions…"/><kbd>⌘ K</kbd></form><nav className="header-actions" aria-label="Account actions"><Link href={accountHref} aria-label={session.authenticated?'My account':'Sign in'} className={isActive('/account')?'active':''}><UserRound/></Link><Link href="/account/wishlist" aria-label="Wishlist" className={`cart-link ${isActive('/account/wishlist')?'active':''}`}><Heart/>{wishlist.length>0&&<span>{wishlist.length}</span>}</Link><Link href="/cart" aria-label={`Cart with ${count} items`} className={`cart-link ${isActive('/cart')?'active':''}`}><ShoppingBag/>{count>0&&<span>{count}</span>}</Link></nav></div><nav className="main-nav shell" aria-label="Main navigation">{links.map(([label,url])=><Link href={url} key={`${label}-${url}`} className={isActive(url)?'active':''} aria-current={isActive(url)?'page':undefined}>{label}</Link>)}<Link href="/shop?sort=sale" className="sale-link">The Gift Sale</Link></nav></header>{open&&<div className="mobile-drawer" role="dialog" aria-modal="true" aria-label="Main menu"><button onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button><Logo/><form action="/search" className="search-box"><Search size={18}/><input name="q" aria-label="Search GiftMitra" placeholder="Search GiftMitra"/></form>{session.authenticated&&<div className="mobile-profile"><span><UserRound/></span><div><small>WELCOME BACK</small><b>{session.fullName}</b></div></div>}<nav>{links.map(([label,url])=><Link className={isActive(url)?'active':''} aria-current={isActive(url)?'page':undefined} onClick={()=>setOpen(false)} href={url} key={`${label}-${url}`}>{label}<span>→</span></Link>)}</nav><div className="mobile-account-actions">{session.authenticated?<><Link href="/account" className="button button-primary" onClick={()=>setOpen(false)}><Home/>My account</Link><Link href="/account/orders" className="button button-soft" onClick={()=>setOpen(false)}><PackageSearch/>Track orders</Link></>:<Link href="/login" className="button button-primary" onClick={()=>setOpen(false)}><LogIn/>Sign in to your account</Link>}</div></div>}</>;
}
export function SiteFooter(){const[config,setConfig]=useState<StoreConfig>({});useEffect(()=>{fetch('/api/storefront-config').then(async response=>(await response.json())as StoreConfig).then(setConfig).catch(()=>{})},[]);const store=config.settings?.store;const social=Object.entries(config.settings?.social??{}).filter(([,url])=>url);return <footer className="footer"><div className="shell footer-grid"><div><Logo/><p>Joyful gifting, thoughtfully curated in India. Every box is made to feel personal.</p><div className="footer-social">{social.length?social.map(([name,url])=><a key={name} href={url} target="_blank" rel="noreferrer">{name}</a>):<><span>Instagram</span><span>Pinterest</span><span>Facebook</span></>}</div>{store?.supportEmail&&<a href={`mailto:${store.supportEmail}`}>{store.supportEmail}</a>}{store?.supportPhone&&<a href={`tel:${store.supportPhone}`}>{store.supportPhone}</a>}</div><div><h3>Shop</h3><Link href="/">Home</Link><Link href="/shop">All gifts</Link><Link href="/occasion/birthday">Birthdays</Link><Link href="/category/personalised-gifts">Personalised</Link><Link href="/hamper-builder">Build a hamper</Link></div><div><h3>Help</h3><Link href="/track-order">Track an order</Link><Link href="/contact">Contact us</Link><Link href="/pages/shipping-policy">Shipping</Link><Link href="/pages/returns">Returns</Link><Link href="/pages/faqs">FAQs</Link></div><div><h3>A little joy in your inbox</h3><p>Gifting ideas, launch notes and members-only offers.</p><form action="/api/newsletter" method="post" className="newsletter"><input name="email" type="email" required placeholder="Email address"/><button aria-label="Subscribe">→</button></form></div></div><div className="shell footer-bottom"><span>© 2026 {store?.name??'GiftMitra'}</span><span>Secure payments · Made with care</span></div></footer>}
export function StorefrontFrame({children}:{children:React.ReactNode}){return <><SiteHeader/>{children}<SiteFooter/></>}
